// backend/scripts/seedMumbaiInfluencers.js
import dotenv from "dotenv";
import mongoose from "mongoose";
import bcrypt from "bcryptjs";
import connectDB from "../config/db.js";

import User from "../models/User.js";
import InfluencerProfile from "../models/InfluencerProfile.js";
import RateCard from "../models/RateCard.js";
import InstagramCache from "../models/InstagramCache.js";
import CollaborationRequest from "../models/CollaborationRequest.js";
import Collaboration from "../models/Collaboration.js";
import Review from "../models/Review.js";

import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
dotenv.config({ path: path.resolve(__dirname, "../.env") });
dotenv.config();

export const MUMBAI_INFLUENCERS_DATA = [
  {
    name: "Viraj Ghelani",
    email: "viraj.ghelani@influenza.io",
    handle: "@viraj_ghelani",
    cleanHandle: "viraj_ghelani",
    title: "Digital Creator & Comedian",
    bio: "Content creator from SoBo—South Borivali 🎬 Comedian & Actor. Known for relatable Gujarati & Mumbai household humor and blockbuster skits.",
    category: "Entertainment & Comedy",
    categories: ["Entertainment & Comedy", "Acting", "Lifestyle", "Comedy"],
    followers: 1450000,
    verified: true,
    gender: "Male",
    ethnicity: "South Asian / Indian",
    languages: ["Hindi", "Gujarati", "English", "Marathi"],
    locality: "Borivali, Mumbai",
    line1: "Shimpoli Road, Borivali West",
    city: "Mumbai",
    state: "Maharashtra",
    country: "India",
    postcode: "400092",
    phoneNumber: "+91 98201 11223",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=600&auto=format&fit=crop&q=80",
    coverPhoto: "https://images.unsplash.com/photo-1514565131-fce0801e5785?w=1200&auto=format&fit=crop&q=80",
    basePrice: 720,
    rates: { post: 60000, reel: 120000, story: 35000 },
    avgLikes: 85000,
    avgComments: 1400,
    avgViews: 420000,
    topPosts: [
      {
        id: "vg_post_1",
        caption: "Gujarati moms when you cough once in the house 😭😂 #Relatable #MumbaiHumor #SoBo",
        likes: 125000,
        comments: 1850,
        views: 650000,
        url: "https://www.instagram.com/viraj_ghelani/",
        isVideo: true,
      },
      {
        id: "vg_post_2",
        caption: "Taking auto rickshaws in Mumbai rains is an extreme sport 🌧️🚕",
        likes: 95000,
        comments: 1320,
        views: 480000,
        url: "https://www.instagram.com/viraj_ghelani/",
        isVideo: true,
      },
      {
        id: "vg_post_3",
        caption: "On set shooting my next sketch! Big announcements coming soon ✨",
        likes: 78000,
        comments: 940,
        views: 320000,
        url: "https://www.instagram.com/viraj_ghelani/",
        isVideo: false,
      },
    ],
    niche: "Comedy & Entertainment",
    passions: "Sketch comedy, acting, relatable Mumbai youth culture, film production",
  },
  {
    name: "Prajakta Koli",
    email: "mostlysane@influenza.io",
    handle: "@mostlysane",
    cleanHandle: "mostlysane",
    title: "Creator, Actor & Author",
    bio: "Creator | Actor (Mismatched, JugJugg Jeeyo) | Author | UNDP Youth Climate Champion. Relatable everyday storytelling from Mumbai to the world.",
    category: "Entertainment & Comedy",
    categories: ["Entertainment & Comedy", "Acting", "Lifestyle", "Youth Culture"],
    followers: 8700000,
    verified: true,
    gender: "Female",
    ethnicity: "South Asian / Indian",
    languages: ["Hindi", "English", "Marathi"],
    locality: "Thane, Mumbai",
    line1: "Ghodbunder Road, Thane West",
    city: "Mumbai",
    state: "Maharashtra",
    country: "India",
    postcode: "400607",
    phoneNumber: "+91 98202 22334",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=600&auto=format&fit=crop&q=80",
    coverPhoto: "https://images.unsplash.com/photo-1518495973542-4542c06a5843?w=1200&auto=format&fit=crop&q=80",
    basePrice: 1800,
    rates: { post: 150000, reel: 350000, story: 90000 },
    avgLikes: 280000,
    avgComments: 2900,
    avgViews: 1500000,
    topPosts: [
      {
        id: "pk_post_1",
        caption: "Dimple Ahuja back on set! Season prep in full swing 🎬☕ #Mismatched",
        likes: 380000,
        comments: 4200,
        views: 2100000,
        url: "https://www.instagram.com/mostlysane/",
        isVideo: false,
      },
      {
        id: "pk_post_2",
        caption: "Types of people at every Mumbai wedding 💃🍛",
        likes: 310000,
        comments: 3100,
        views: 1800000,
        url: "https://www.instagram.com/mostlysane/",
        isVideo: true,
      },
      {
        id: "pk_post_3",
        caption: "Speaking at the UN Youth Forum on sustainable future & youth impact 🌍✨",
        likes: 240000,
        comments: 2150,
        views: 950000,
        url: "https://www.instagram.com/mostlysane/",
        isVideo: false,
      },
    ],
    niche: "Entertainment & Acting",
    passions: "Acting, digital storytelling, youth empowerment, literature",
  },
  {
    name: "Ranveer Allahbadia",
    email: "beerbiceps@influenza.io",
    handle: "@beerbiceps",
    cleanHandle: "beerbiceps",
    title: "Podcaster, Entrepreneur & Fitness Creator",
    bio: "Host of The Ranveer Show (TRS) | Co-Founder @monkentertainment & @levelsupermind | Exploring self-improvement, health, mindfulness & business.",
    category: "Health & Fitness",
    categories: ["Health & Fitness", "Business & Finance", "Self-Improvement", "Podcasting"],
    followers: 4200000,
    verified: true,
    gender: "Male",
    ethnicity: "South Asian / Indian",
    languages: ["English", "Hindi"],
    locality: "Lower Parel, Mumbai",
    line1: "Senapati Bapat Marg, Lower Parel",
    city: "Mumbai",
    state: "Maharashtra",
    country: "India",
    postcode: "400013",
    phoneNumber: "+91 98203 33445",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=600&auto=format&fit=crop&q=80",
    coverPhoto: "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=1200&auto=format&fit=crop&q=80",
    basePrice: 1450,
    rates: { post: 120000, reel: 280000, story: 75000 },
    avgLikes: 160000,
    avgComments: 1800,
    avgViews: 950000,
    topPosts: [
      {
        id: "rb_post_1",
        caption: "The power of morning cold showers & deep breathwork. Try this routine for 7 days ⚡🧘‍♂️",
        likes: 210000,
        comments: 2400,
        views: 1200000,
        url: "https://www.instagram.com/beerbiceps/",
        isVideo: true,
      },
      {
        id: "rb_post_2",
        caption: "Deep dive with ISRO scientists on TRS Episode 420! Inspiring conversation on India's future 🚀",
        likes: 185000,
        comments: 1900,
        views: 980000,
        url: "https://www.instagram.com/beerbiceps/",
        isVideo: false,
      },
      {
        id: "rb_post_3",
        caption: "Consistency beats talent every single time. Keep grinding in silence 🦾",
        likes: 140000,
        comments: 1350,
        views: 820000,
        url: "https://www.instagram.com/beerbiceps/",
        isVideo: true,
      },
    ],
    niche: "Fitness & Self-Improvement",
    passions: "Podcasting, functional fitness, meditation, entrepreneurship",
  },
  {
    name: "Chef Sanjyot Keer",
    email: "chefsanjyot@influenza.io",
    handle: "@sanjyotkeer",
    cleanHandle: "sanjyotkeer",
    title: "Celebrity Chef & Founder Your Food Lab",
    bio: "Founder @yourfoodlab | Chef | Forbes Tycoons of Tomorrow | Bringing cinematic high-production recipe creation to Indian kitchens.",
    category: "Food & Beverage",
    categories: ["Food & Beverage", "Culinary Arts", "Lifestyle"],
    followers: 3400000,
    verified: true,
    gender: "Male",
    ethnicity: "South Asian / Indian",
    languages: ["Hindi", "English", "Marathi"],
    locality: "Andheri West, Mumbai",
    line1: "Lokhandwala Complex, Andheri West",
    city: "Mumbai",
    state: "Maharashtra",
    country: "India",
    postcode: "400053",
    phoneNumber: "+91 98204 44556",
    avatar: "https://images.unsplash.com/photo-1577219491135-ce391730fb2c?w=600&auto=format&fit=crop&q=80",
    coverPhoto: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=1200&auto=format&fit=crop&q=80",
    basePrice: 1150,
    rates: { post: 95000, reel: 220000, story: 55000 },
    avgLikes: 110000,
    avgComments: 1200,
    avgViews: 800000,
    topPosts: [
      {
        id: "sk_post_1",
        caption: "Street-style Mumbai Pav Bhaji from scratch! The secret spice blend revealed 🥘✨ #YFLKitchen",
        likes: 175000,
        comments: 1890,
        views: 1250000,
        url: "https://www.instagram.com/sanjyotkeer/",
        isVideo: true,
      },
      {
        id: "sk_post_2",
        caption: "Crispy Paneer Katsu Burger with spicy sriracha glaze 🍔🔥",
        likes: 130000,
        comments: 1450,
        views: 890000,
        url: "https://www.instagram.com/sanjyotkeer/",
        isVideo: true,
      },
      {
        id: "sk_post_3",
        caption: "Culinary shoot days are the best days. Testing 5 festive dessert recipes today! 🍰",
        likes: 92000,
        comments: 870,
        views: 540000,
        url: "https://www.instagram.com/sanjyotkeer/",
        isVideo: false,
      },
    ],
    niche: "Culinary Arts & Gourmet Food",
    passions: "Recipe development, cinematography, regional Indian spices, kitchen aesthetics",
  },
  {
    name: "Aashna Shroff",
    email: "aashna.shroff@influenza.io",
    handle: "@aashnashroff",
    cleanHandle: "aashnashroff",
    title: "Luxury Fashion & Beauty Influencer",
    bio: "Cosmopolitan Luxury Fashion Influencer of the Year | The Snob Journal | Curating effortless chic aesthetics, skincare rituals & travel diaries in Mumbai.",
    category: "Fashion & Style",
    categories: ["Fashion & Style", "Beauty & Skincare", "Luxury Lifestyle"],
    followers: 1050000,
    verified: true,
    gender: "Female",
    ethnicity: "South Asian / Indian",
    languages: ["English", "Hindi"],
    locality: "Juhu, Mumbai",
    line1: "Juhu Tara Road, Juhu",
    city: "Mumbai",
    state: "Maharashtra",
    country: "India",
    postcode: "400049",
    phoneNumber: "+91 98205 55667",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=80",
    coverPhoto: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=1200&auto=format&fit=crop&q=80",
    basePrice: 960,
    rates: { post: 80000, reel: 160000, story: 45000 },
    avgLikes: 55000,
    avgComments: 620,
    avgViews: 310000,
    topPosts: [
      {
        id: "as_post_1",
        caption: "Golden hour in Paris wearing bespoke silk couture ✨🤍 #PFW #OOTD",
        likes: 82000,
        comments: 890,
        views: 450000,
        url: "https://www.instagram.com/aashnashroff/",
        isVideo: false,
      },
      {
        id: "as_post_2",
        caption: "5 everyday skincare holy-grails for glass skin in humid Mumbai weather 🧴💧",
        likes: 64000,
        comments: 710,
        views: 380000,
        url: "https://www.instagram.com/aashnashroff/",
        isVideo: true,
      },
      {
        id: "as_post_3",
        caption: "Styling 1 trench coat in 4 different aesthetic silhouettes 🧥👠",
        likes: 51000,
        comments: 540,
        views: 290000,
        url: "https://www.instagram.com/aashnashroff/",
        isVideo: true,
      },
    ],
    niche: "Luxury Fashion & Skincare",
    passions: "High fashion styling, clean beauty routines, luxury travel, editorial creative direction",
  },
  {
    name: "Radhika Seth",
    email: "radhika.seth@influenza.io",
    handle: "@radhikasethh",
    cleanHandle: "radhikasethh",
    title: "Model, Actress & Fashion Creator",
    bio: "Story of a girl who chased the sunset ✨ Mumbai. Clean silhouettes, minimalist aesthetics, and editorial fashion.",
    category: "Fashion & Style",
    categories: ["Fashion & Style", "Beauty & Skincare", "Acting", "Lifestyle"],
    followers: 1150000,
    verified: true,
    gender: "Female",
    ethnicity: "South Asian / Indian",
    languages: ["English", "Hindi"],
    locality: "Bandra West, Mumbai",
    line1: "Pali Hill, Bandra West",
    city: "Mumbai",
    state: "Maharashtra",
    country: "India",
    postcode: "400050",
    phoneNumber: "+91 98206 66778",
    avatar: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=600&auto=format&fit=crop&q=80",
    coverPhoto: "https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=1200&auto=format&fit=crop&q=80",
    basePrice: 840,
    rates: { post: 70000, reel: 140000, story: 40000 },
    avgLikes: 62000,
    avgComments: 710,
    avgViews: 340000,
    topPosts: [
      {
        id: "rs_post_1",
        caption: "Sunset strolls through Bandra lanes in vintage denim 🌅🕊️",
        likes: 79000,
        comments: 880,
        views: 410000,
        url: "https://www.instagram.com/radhikasethh/",
        isVideo: false,
      },
      {
        id: "rs_post_2",
        caption: "Morning Pilates session followed by iced matcha 🍵🧘‍♀️",
        likes: 68000,
        comments: 720,
        views: 360000,
        url: "https://www.instagram.com/radhikasethh/",
        isVideo: true,
      },
      {
        id: "rs_post_3",
        caption: "Campaign shoot preview with Vogue India! Grateful for this creative team ✨",
        likes: 59000,
        comments: 640,
        views: 310000,
        url: "https://www.instagram.com/radhikasethh/",
        isVideo: false,
      },
    ],
    niche: "Minimalist Fashion & Beauty",
    passions: "Editorial modeling, wellness, vintage apparel, travel journals",
  },
  {
    name: "Saloni Kukreja",
    email: "saloni.kukreja@influenza.io",
    handle: "@salonikukreja",
    cleanHandle: "salonikukreja",
    title: "Chef, Culinary Explorer & Entrepreneur",
    bio: "Chef | Entrepreneur @induicecream | Forbes 30 Under 30 Asia | Started Food of Mumbai | Innovative recipes & culinary culture.",
    category: "Food & Beverage",
    categories: ["Food & Beverage", "Culinary Arts", "Entrepreneurship"],
    followers: 1120000,
    verified: true,
    gender: "Female",
    ethnicity: "South Asian / Indian",
    languages: ["English", "Hindi"],
    locality: "Khar West, Mumbai",
    line1: "14th Road, Khar West",
    city: "Mumbai",
    state: "Maharashtra",
    country: "India",
    postcode: "400052",
    phoneNumber: "+91 98207 77889",
    avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=600&auto=format&fit=crop&q=80",
    coverPhoto: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=1200&auto=format&fit=crop&q=80",
    basePrice: 660,
    rates: { post: 55000, reel: 115000, story: 30000 },
    avgLikes: 48000,
    avgComments: 530,
    avgViews: 290000,
    topPosts: [
      {
        id: "sl_post_1",
        caption: "The crispiest Garlic Butter Chilli Naan Rolls you will ever make 🧄🌶️",
        likes: 67000,
        comments: 740,
        views: 420000,
        url: "https://www.instagram.com/salonikukreja/",
        isVideo: true,
      },
      {
        id: "sl_post_2",
        caption: "Testing our new artisanal ice cream batch at @induicecream 🍨🍦",
        likes: 54000,
        comments: 590,
        views: 310000,
        url: "https://www.instagram.com/salonikukreja/",
        isVideo: false,
      },
      {
        id: "sl_post_3",
        caption: "Must-visit hidden food gems across Matunga & Fort Mumbai 🍽️",
        likes: 46000,
        comments: 510,
        views: 260000,
        url: "https://www.instagram.com/salonikukreja/",
        isVideo: true,
      },
    ],
    niche: "Culinary Innovation & Artisan Food",
    passions: "Baking, culinary anthropology, ice cream craftsmanship, cafe culture",
  },
  {
    name: "Dhananjay Bhosale",
    email: "dhananjay.tech@influenza.io",
    handle: "@dhananjay_tech",
    cleanHandle: "dhananjay_tech",
    title: "Tech Content Creator & Gadget Reviewer",
    bio: "Full-time Tech content creator 📱 Simplifying gadgets, smartphone camera tests, productivity tools & AI for real people.",
    category: "Tech & Gadgets",
    categories: ["Tech & Gadgets", "Consumer Electronics", "AI & Productivity"],
    followers: 710000,
    verified: true,
    gender: "Male",
    ethnicity: "South Asian / Indian",
    languages: ["Marathi", "Hindi", "English"],
    locality: "Navi Mumbai, Mumbai",
    line1: "Palm Beach Road, Vashi",
    city: "Mumbai",
    state: "Maharashtra",
    country: "India",
    postcode: "400703",
    phoneNumber: "+91 98208 88990",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=600&auto=format&fit=crop&q=80",
    coverPhoto: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=1200&auto=format&fit=crop&q=80",
    basePrice: 540,
    rates: { post: 45000, reel: 90000, story: 25000 },
    avgLikes: 32000,
    avgComments: 450,
    avgViews: 240000,
    topPosts: [
      {
        id: "db_post_1",
        caption: "Top 5 AI tools that will save you 10+ hours every single week 🤖⚡",
        likes: 49000,
        comments: 620,
        views: 390000,
        url: "https://www.instagram.com/dhananjay_tech/",
        isVideo: true,
      },
      {
        id: "db_post_2",
        caption: "Smartphone camera blind test: Flagship vs Midranger in low light! 📸📱",
        likes: 38000,
        comments: 510,
        views: 280000,
        url: "https://www.instagram.com/dhananjay_tech/",
        isVideo: true,
      },
      {
        id: "db_post_3",
        caption: "Desk setup upgrade 2026! Cable management & OLED monitor breakdown 🖥️✨",
        likes: 31000,
        comments: 380,
        views: 190000,
        url: "https://www.instagram.com/dhananjay_tech/",
        isVideo: false,
      },
    ],
    niche: "Smartphones & Tech Productivity",
    passions: "Tech reviews, camera sensor comparisons, coding workflows, gadget unboxings",
  },
  {
    name: "Larissa D'Sa",
    email: "larissa.dsa@influenza.io",
    handle: "@larissa_wlc",
    cleanHandle: "larissa_wlc",
    title: "Travel Filmmaker & Lifestyle Creator",
    bio: "Travel. Jewellery. Design. Life. Curious by profession. Founder @beyond.larissa | Cinematic travel vlogging & lifestyle storytelling.",
    category: "Travel & Adventure",
    categories: ["Travel & Adventure", "Lifestyle", "Fashion & Style"],
    followers: 815000,
    verified: true,
    gender: "Female",
    ethnicity: "South Asian / Indian",
    languages: ["English", "Hindi"],
    locality: "Bandra West, Mumbai",
    line1: "Carter Road, Bandra West",
    city: "Mumbai",
    state: "Maharashtra",
    country: "India",
    postcode: "400050",
    phoneNumber: "+91 98209 99001",
    avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=600&auto=format&fit=crop&q=80",
    coverPhoto: "https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=1200&auto=format&fit=crop&q=80",
    basePrice: 600,
    rates: { post: 50000, reel: 110000, story: 30000 },
    avgLikes: 42000,
    avgComments: 490,
    avgViews: 260000,
    topPosts: [
      {
        id: "ld_post_1",
        caption: "Lost in the mountain mist of Himachal 🏔️🎒 Solo travel essentials video is up!",
        likes: 58000,
        comments: 630,
        views: 340000,
        url: "https://www.instagram.com/larissa_wlc/",
        isVideo: true,
      },
      {
        id: "ld_post_2",
        caption: "Handmade silver jewellery collection drop is finally live at @beyond.larissa 💍✨",
        likes: 44000,
        comments: 480,
        views: 240000,
        url: "https://www.instagram.com/larissa_wlc/",
        isVideo: false,
      },
      {
        id: "ld_post_3",
        caption: "Sunset kayaking off the Konkan coast 🚣‍♀️🌊 Pure peaceful magic",
        likes: 39000,
        comments: 410,
        views: 210000,
        url: "https://www.instagram.com/larissa_wlc/",
        isVideo: true,
      },
    ],
    niche: "Cinematic Travel & Boutique Design",
    passions: "Filmmaking, adventure exploration, artisan jewellery design, wellness",
  },
  {
    name: "Yasmin Karachiwala",
    email: "yasmin.karachiwala@influenza.io",
    handle: "@yasminkarachiwala",
    cleanHandle: "yasminkarachiwala",
    title: "Celebrity Fitness Instructor & Pilates Pioneer",
    bio: "Pioneer of Pilates in India | Founder @ykbipilates | Transforming fitness & functional wellness for Bollywood & beyond.",
    category: "Health & Fitness",
    categories: ["Health & Fitness", "Wellness", "Celebrity Training"],
    followers: 1080000,
    verified: true,
    gender: "Female",
    ethnicity: "South Asian / Indian",
    languages: ["English", "Hindi"],
    locality: "Bandra, Mumbai",
    line1: "Waterfield Road, Bandra West",
    city: "Mumbai",
    state: "Maharashtra",
    country: "India",
    postcode: "400050",
    phoneNumber: "+91 98210 10102",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=600&auto=format&fit=crop&q=80",
    coverPhoto: "https://images.unsplash.com/photo-1518611012118-696072aa579a?w=1200&auto=format&fit=crop&q=80",
    basePrice: 1020,
    rates: { post: 85000, reel: 175000, story: 50000 },
    avgLikes: 38000,
    avgComments: 410,
    avgViews: 210000,
    topPosts: [
      {
        id: "yk_post_1",
        caption: "5 Pilates reformer exercises for deep core activation & postural alignment 🧘‍♀️💪",
        likes: 52000,
        comments: 540,
        views: 310000,
        url: "https://www.instagram.com/yasminkarachiwala/",
        isVideo: true,
      },
      {
        id: "yk_post_2",
        caption: "Pre-shoot warmup session with Deepika Padukone at the Bandra studio! ✨⚡",
        likes: 47000,
        comments: 490,
        views: 290000,
        url: "https://www.instagram.com/yasminkarachiwala/",
        isVideo: false,
      },
      {
        id: "yk_post_3",
        caption: "Quick 10-minute mobility stretch routine you can do right out of bed 🛌☀️",
        likes: 35000,
        comments: 380,
        views: 180000,
        url: "https://www.instagram.com/yasminkarachiwala/",
        isVideo: true,
      },
    ],
    niche: "Pilates & Celebrity Functional Fitness",
    passions: "Pilates training, spinal rehabilitation, nutrition, athletic conditioning",
  },
];

export async function seedMumbaiInfluencers() {
  try {
    console.log("Connecting to MongoDB Atlas...");
    await connectDB();

    console.log("Seeding real Mumbai-based influencers...");
    const hashedPassword = await bcrypt.hash("password123", 10);

    // Get or create brand demo user for reviews
    let brandUser = await User.findOne({ email: "brand@demo.com" });
    if (!brandUser) {
      brandUser = await User.create({
        name: "Luxe Beauty Collective",
        email: "brand@demo.com",
        password: hashedPassword,
        role: "brand",
      });
    }

    for (const item of MUMBAI_INFLUENCERS_DATA) {
      // 1. Create or Update User
      let user = await User.findOne({ email: item.email });
      if (!user) {
        user = await User.create({
          name: item.name,
          email: item.email,
          password: hashedPassword,
          role: "influencer",
        });
        console.log(`[Created User] ${item.name} (${item.email})`);
      } else {
        user.name = item.name;
        await user.save();
        console.log(`[Updated User] ${item.name} (${item.email})`);
      }

      // 2. Create or Update InfluencerProfile
      const profileData = {
        user: user._id,
        handle: item.handle,
        approved: true,
        categories: item.categories,
        personalInfo: {
          firstName: item.name.split(" ")[0],
          lastName: item.name.split(" ").slice(1).join(" "),
          title: item.title,
          avatar: item.avatar,
          coverPhoto: item.coverPhoto,
          coverPhotos: [item.coverPhoto],
          gender: item.gender,
          ethnicity: item.ethnicity,
          languages: item.languages,
          petOwner: "Yes",
          bio: item.bio,
        },
        address: {
          line1: item.line1,
          city: item.city,
          county: "Mumbai Suburban",
          state: item.state,
          postcode: item.postcode,
          country: item.country,
          phoneNumber: item.phoneNumber,
        },
        matchProfile: {
          campaignActive: true,
          invitationsActive: true,
          collaborationFormats: [
            "Instagram Reels",
            "Instagram Stories",
            "Instagram Post",
            "Dedicated Video",
          ],
          paymentType: "paid",
          minAskingPrice: Math.round(item.basePrice * 0.8),
          maxAskingPrice: Math.round(item.basePrice * 2.5),
          bio: item.bio,
          passions: item.passions,
          topics: [item.niche, "Brand Collaborations", "Product Reviews"],
          niche: [item.niche, "Mumbai Creators", "Reels Creators"],
          leadTimeDays: 5,
          preferredCompanies: ["Zomato", "Nykaa", "OnePlus", "Myntra", "Swiggy", "Boat"],
          interestedBrands: ["Nike", "L'Oréal", "Samsung", "Tata CliQ", "Mamaearth"],
          audienceGender: item.gender === "Female" ? "65% Female, 35% Male" : "45% Female, 55% Male",
          audienceAgeRange: "18-34",
          audience: ["Gen Z", "Millennials", "Urban Youth"],
          followersLocations: ["IN", "Mumbai", "Delhi", "Pune", "Bengaluru"],
        },
        socialAccounts: [
          {
            platform: "Instagram",
            handle: item.handle,
            followers: item.followers,
            verified: item.verified,
            connected: true,
            engagementRate: Number(((item.avgLikes / item.followers) * 100).toFixed(2)),
            avgLikes: item.avgLikes,
            avgComments: item.avgComments,
          },
        ],
        payoutInfo: {
          method: "upi",
          accountHolderName: item.name,
          bankName: "HDFC Bank",
          accountNumber: "50100492817263",
          ifscOrRouting: "HDFC0000123",
          upiId: `${item.cleanHandle}@okhdfcbank`,
          currency: "INR",
          isConfigured: true,
        },
        packages: [
          {
            id: `pkg_${item.cleanHandle}_1`,
            title: "1x Dedicated 60s Instagram Reel",
            contentType: "Reel",
            count: 1,
            duration: 1,
            durationUnit: "Minutes",
            price: item.rates.reel,
            description: "High-production vertical Reel with organic integration, product placement & link sticker.",
          },
          {
            id: `pkg_${item.cleanHandle}_2`,
            title: "3x Interactive Instagram Stories",
            contentType: "Story",
            count: 3,
            duration: 15,
            durationUnit: "Seconds",
            price: item.rates.story,
            description: "3 sequence stories featuring unboxing, direct CTA sticker, and discount code.",
          },
          {
            id: `pkg_${item.cleanHandle}_3`,
            title: "1x High-Resolution Carousel Post",
            contentType: "Post",
            count: 1,
            duration: 1,
            durationUnit: "Posts",
            price: item.rates.post,
            description: "Aesthetic multi-slide photo carousel with in-depth review and brand tagging.",
          },
        ],
        isProfileComplete: true,
      };

      const profile = await InfluencerProfile.findOneAndUpdate(
        { user: user._id },
        profileData,
        { upsert: true, new: true }
      );
      console.log(`[Synced Profile] ${item.name} (${item.handle}) - ${item.city}, ${item.country}`);

      // 3. Create or Update RateCard
      await RateCard.findOneAndUpdate(
        { influencer: user._id },
        {
          influencer: user._id,
          followers: item.followers,
          avgLikes: item.avgLikes,
          avgComments: item.avgComments,
          nicheId: item.niche,
          marketId: "Mumbai, India",
          rates: item.rates,
          packages: profileData.packages,
        },
        { upsert: true, new: true }
      );
      console.log(`[Synced RateCard] ${item.name} rates: Reel ₹${item.rates.reel.toLocaleString()}`);

      // 4. Update InstagramCache for 0ms lookup latency
      await InstagramCache.findOneAndUpdate(
        { handle: item.cleanHandle },
        {
          handle: item.cleanHandle,
          fullName: item.name,
          profilePicUrl: item.avatar,
          rawProfilePicUrl: item.avatar,
          biography: item.bio,
          verified: item.verified,
          followers: item.followers,
          avgLikes: item.avgLikes,
          avgComments: item.avgComments,
          avgViews: item.avgViews,
          topPosts: item.topPosts,
          lastFetchedAt: new Date(),
        },
        { upsert: true, new: true }
      );
      console.log(`[Synced InstagramCache] @${item.cleanHandle} (Followers: ${item.followers.toLocaleString()})`);
    }

    console.log("\n✅ All 10 Mumbai influencers successfully seeded into database & cache!");
    process.exit(0);
  } catch (error) {
    console.error("❌ Error seeding Mumbai influencers:", error);
    process.exit(1);
  }
}

// Execute if run directly
if (process.argv[1]?.endsWith("seedMumbaiInfluencers.js")) {
  seedMumbaiInfluencers();
}
