import { Search, DollarSign, MessageSquare, TrendingUp, UserCheck, Video, Send, Award } from "lucide-react";

export const brandSteps = [
  {
    id: "brand-1",
    number: "01",
    icon: Search,
    title: "Discover & Match",
    description: "Search verified creators with live ER%, authentic follower demographics, and niche compatibility.",
    tag: "Smart Discovery",
    color: "#FF1475",
    rotate: "-rotate-2",
  },
  {
    id: "brand-2",
    number: "02",
    icon: DollarSign,
    title: "Choose Deliverables",
    description: "Select transparent fixed-rate packages for Reels, UGC videos, and Stories with verified pricing in ₹.",
    tag: "Fixed Rates",
    color: "#8D64ED",
    rotate: "rotate-2",
  },
  {
    id: "brand-3",
    number: "03",
    icon: MessageSquare,
    title: "Direct Collaboration",
    description: "Send campaign proposals, coordinate in real-time chat, and review content drafts seamlessly.",
    tag: "1-Click Approvals",
    color: "#1E9DF1",
    rotate: "-rotate-2",
  },
  {
    id: "brand-4",
    number: "04",
    icon: TrendingUp,
    title: "Measure Live ROI",
    description: "Track live campaign performance, verified reach, engagement rates, and real sales ROI on your dashboard.",
    tag: "Live Analytics",
    color: "#00E599",
    rotate: "rotate-2",
  },
];

export const creatorSteps = [
  {
    id: "creator-1",
    number: "01",
    icon: UserCheck,
    title: "Setup Creator Profile",
    description: "Connect your Instagram handle, set custom pricing packages in ₹, and get your InfluRate™ score.",
    tag: "Quick Onboarding",
    color: "#FF1475",
    rotate: "-rotate-2",
  },
  {
    id: "creator-2",
    number: "02",
    icon: Video,
    title: "Showcase Portfolio",
    description: "Upload your top high-converting UGC reels and videos to your public creator showcase.",
    tag: "Public Showcase",
    color: "#8D64ED",
    rotate: "rotate-2",
  },
  {
    id: "creator-3",
    number: "03",
    icon: Send,
    title: "Receive Brand Deals",
    description: "Get discovered by top brands and receive paid collaboration requests directly in your inbox.",
    tag: "Direct Bookings",
    color: "#1E9DF1",
    rotate: "-rotate-2",
  },
  {
    id: "creator-4",
    number: "04",
    icon: Award,
    title: "Deliver & Get Paid",
    description: "Submit draft deliverables, complete brand milestones, and build verified reputation badges.",
    tag: "Verified Reviews",
    color: "#00E599",
    rotate: "rotate-2",
  },
];
